/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_midorigenerator_free: (a: number, b: number) => void;
export const __wbg_midorinaturegenerator_free: (a: number, b: number) => void;
export const generate_nature_preview_from_toml: (a: number, b: number, c: number, d: number) => [number, number, number];
export const generate_tree_from_toml: (a: number, b: number, c: bigint) => [number, number, number];
export const midorigenerator_exportGltf: (a: number, b: bigint, c: number, d: number, e: number) => [number, number, number];
export const midorigenerator_export_glb: (a: number, b: bigint, c: number) => [number, number, number];
export const midorigenerator_fromJson: (a: any) => [number, number, number];
export const midorigenerator_generate: (a: number, b: bigint) => [number, number, number];
export const midorigenerator_generateMaps: (a: number) => [number, number, number];
export const midorigenerator_generate_lod: (a: number, b: bigint, c: number) => [number, number, number];
export const midorigenerator_get_stats: (a: number, b: bigint) => [number, number, number];
export const midorigenerator_metadata: (a: number) => [number, number, number];
export const midorigenerator_name: (a: number) => [number, number];
export const midorigenerator_new: (a: number, b: number) => [number, number, number];
export const midorigenerator_toJson: (a: number) => [number, number, number];
export const midorigenerator_toToml: (a: number) => [number, number, number, number];
export const midorinaturegenerator_name: (a: number) => [number, number];
export const midorinaturegenerator_new: (a: number, b: number) => [number, number, number];
export const midorinaturegenerator_preview: (a: number, b: number, c: number) => [number, number, number];
export const init: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
